// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface Item
 */
export interface Item {
    /**
     *
     * @type {string}
     * @memberof Item
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Item
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof Item
     */
    subtitle: string;
    /**
     *
     * @type {string}
     * @memberof Item
     */
    subtitleLabel: string;
    /**
     *
     * @type {string}
     * @memberof Item
     */
    description?: string;
    /**
     *
     * @type {object}
     * @memberof Item
     */
    thumbnail: string;
    /**
     *
     * @type {Array<object>}
     * @memberof Item
     */
    promoimages?: Array<object>;
    /**
     *
     * @type {object}
     * @memberof Item
     */
    itemcategories?: object;
    /**
     *
     * @type {object}
     * @memberof Item
     */
    seller?: object;
}


