// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewItem
 */
export interface NewItem {
    /**
     * 
     * @type {string}
     * @memberof NewItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof NewItem
     */
    itemcategories?: string;
    /**
     * 
     * @type {string}
     * @memberof NewItem
     */
    seller?: string;
}


