// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NewSeller
 */
export interface NewSeller {
    /**
     * 
     * @type {string}
     * @memberof NewSeller
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NewSeller
     */
    primarycategory?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewSeller
     */
    sellerpoints?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewSeller
     */
    items?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof NewSeller
     */
    description?: string;
}


