// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Orderitem
 */
export interface Orderitem {
    /**
     * 
     * @type {string}
     * @memberof Orderitem
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Orderitem
     */
    amount: number;
    /**
     * 
     * @type {object}
     * @memberof Orderitem
     */
    pointitem?: object;
}


