// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface Routestoporder
 */
export interface Routestoporder {
    /**
     *
     * @type {string}
     * @memberof Routestoporder
     */
    id: string;
    /**
     *
     * @type {object}
     * @memberof Routestoporder
     */
    orderitems?: object;
    /**
     *
     * @type {string}
     * @memberof Routestoporder
     */
    status?: RoutestoporderStatusEnum;
    /**
     *
     * @type {object}
     * @memberof Routestoporder
     */
    routestop?: object;
}

/**
    * @export
    * @enum {string}
    */
export enum RoutestoporderStatusEnum {
    Available = 'available',
    Locked = 'locked',
    Paid = 'paid',
    Delivered = 'delivered'
}



