// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Routestop
 */
export interface Routestop {
    /**
     * 
     * @type {string}
     * @memberof Routestop
     */
    id: string;
    /**
     * 
     * @type {object}
     * @memberof Routestop
     */
    station?: object;
    /**
     * 
     * @type {string}
     * @memberof Routestop
     */
    arrivaltime: string;
    /**
     * 
     * @type {string}
     * @memberof Routestop
     */
    departuretime: string;
    /**
     * 
     * @type {object}
     * @memberof Routestop
     */
    route?: object;
}


