// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Supportticket
 */
export interface Supportticket {
    /**
     * 
     * @type {string}
     * @memberof Supportticket
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Supportticket
     */
    reason?: SupportticketReasonEnum;
    /**
     * 
     * @type {object}
     * @memberof Supportticket
     */
    orderitem?: object;
}

/**
    * @export
    * @enum {string}
    */
export enum SupportticketReasonEnum {
    Incorrectitems = 'incorrectitems',
    Paymentissue = 'paymentissue',
    Courierlate = 'courierlate'
}



