// tslint:disable
/// <reference path="../custom.d.ts" />
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsersPermissionsUser
 */
export interface UsersPermissionsUser {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsUser
     */
    provider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUser
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPermissionsUser
     */
    blocked?: boolean;
    /**
     * 
     * @type {object}
     * @memberof UsersPermissionsUser
     */
    role?: object;
    /**
     * 
     * @type {object}
     * @memberof UsersPermissionsUser
     */
    routetickets?: object;
}


